services:
  - type: web
    name: shark-vendas
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y unzip
      unzip vendas.zip
      npm install
    startCommand: node index.js
    envVars:
      - key: TOKEN
        sync: false
