services:
  - type: web
    name: shark-vendas
    runtime: node
    buildCommand: |
      unzip vendas.zip -d ./
      npm install
    startCommand: node index.js
    envVars:
      - key: TOKEN
        sync: false 
